disabled = false
locale = "en"
label = "English"
weight = 1
title = "Joshua Casey - Digital Rights Activist and Video Game Streamer"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "January 2 2006"
  logo = "/android-chrome-512x512.png"
  secondaryLogo = "https://sharex.dftba.xyz/profilepic.jpg"
  description = "Joshua is an autistic nerd, video game streamer and digital rights activist that is passionate about human rights, free speech, anti-censorship, privacy, autistic people’s rights, sex worker’s rights, criminal punishment system reform, prevention of sexual abuse, and climate change and generally just making the world a better place for those of us that aren't billionaires 😆"
  # copyright = ""© 2013-2026, Joshua Casey, All Rights Reserved""

[params.author]
  name = "Joshua Casey"
  email = "joshua@joshuacasey.net"
#   image = "img/blowfish_logo.png"
#   imageQuality = 96
  headline = "Digital Rights Activist and Video Game Streamer"
#   bio = "Joshua is a nerdy video game streamer and is passionate about human rights, free speech, and anti-censorship."
  links = [
#     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
#     { apple = "https://www.apple.com" },
#     { blogger = "https://username.blogspot.com/" },
     { bluesky = "https://bsky.app/profile/joshuacasey.net" },
#     { codepen = "https://codepen.io/username" },
#     { dev = "https://dev.to/username" },
     { discord = "https://discord.com/users/1049691096483123240" },
#     { dribbble = "https://dribbble.com/username" },
#     { facebook = "https://facebook.com/username" },
#     { flickr = "https://www.flickr.com/photos/username/" },
#     { foursquare = "https://foursquare.com/username" },
     { git = "https://tangled.org/joshuacasey.net"},
     { github = "https://github.com/JoshuaACasey" },
#     { github_gist = "https://gist.github.com/username" },
#     { gitlab = "https://gitlab.com/username" },
#     { google = "https://www.google.com/" },
#     { hashnode = "https://username.hashnode.dev" },
#     { instagram = "https://instagram.com/username" },
#     { itch-io = "https://username.itch.io" },
      { key = "https://keytrace.dev/joshuacasey.net" },
#     { keybase = "https://keybase.io/username" },
     { keyoxide = "https://keyoxide.org/aspe:keyoxide.org:AXPQOMLX2FDPP7TJXNIGOZ47YA" },
#     { kickstarter = "https://www.kickstarter.com/profile/username" },
#     { lastfm = "https://lastfm.com/user/username" },
    #{ lemmy = "https://lemmy.world/u/JoshuaCasey" },
     { linkedin = "https://sifa.id/p/joshuacasey.net" },
     { mastodon = "https://social.dftba.xyz/@JoshuaACasey" },
     { matrix = "https://matrix.to/#/@JoshuaCasey:matrix.org" },
#     { medium = "https://medium.com/username" },
#     { microsoft = "https://www.microsoft.com/" },
#     { orcid = "https://orcid.org/userid" },
#     { patreon = "https://www.patreon.com/username" },
#     { pinterest = "https://pinterest.com/username" },
#     { reddit = "https://reddit.com/user/username" },
#     { researchgate = "https://www.researchgate.net/profile/username" },
#     { signal = "https://signal.me/#eu/userid" },
#     { slack = "https://workspace.url/team/userid" },
#     { snapchat = "https://snapchat.com/add/username" },
#     { soundcloud = "https://soundcloud.com/username" },
#     { spotify = "https://open.spotify.com/user/userid" },
#     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
     { steam = "https://steamcommunity.com/id/JoshuaACasey/" },
#     { strava = "https://www.strava.com/athletes/username" },
#     { telegram = "https://t.me/username" },
#     { threads = "https://www.threads.net/@username" },
#     { tiktok = "https://tiktok.com/@username" },
     { gift = "https://throne.com/JoshuaACasey" },
#     { tumblr = "https://username.tumblr.com" },
     { twitch = "https://twitch.tv/JoshuaACasey" },
#     { untappd = "https://untappd.com/user/username" },
#     { twitter = "https://twitter.com/username" },
#     { x-twitter = "https://twitter.com/username" },
#     { whatsapp = "https://wa.me/phone-number" },
#     { youtube = "https://youtube.com/username" },
#     { ko-fi = "https://ko-fi.com/username" },
#     { codeberg = "https://codeberg.org/username"},
#     { printables = "https://www.printables.com/@username"},
     { link = "https://links.joshuacasey.net" },
#    { email = "mailto:hello@your_domain.com" },
     { rss-square = "https://joshuacasey.net/posts/index.xml" },
]
